# Generated by Django 5.2 on 2025-10-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('order', 'Order'), ('menu', 'Menu'), ('review', 'Review'), ('system', 'System')], default='system', max_length=20),
        ),
    ]
