# Generated by Django 5.2 on 2025-10-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('order', 'Order'), ('menu', 'Menu'), ('review', 'Review'), ('attendance', 'Attendance'), ('system', 'System')], default='system', max_length=20),
        ),
    ]
