# Generated by Django 5.2 on 2025-10-16 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_table_order_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('ready', 'Ready'), ('served', 'Served'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
