# Generated by Django 5.2 on 2025-10-19 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
    ]
