# Generated by Django 5.2 on 2025-10-27 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_status'),
        ('users', '0008_staff_vehicle_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_boy',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'DeliveryBoy'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='users.staff'),
        ),
    ]
