# Generated by Django 5.2 on 2025-10-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_delivery_boy'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='preparation_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='preparation_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
