# Generated by Django 5.2 on 2025-11-10 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_preparation_end_order_preparation_start'),
        ('users', '0010_alter_staff_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='waiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='users.staff'),
        ),
    ]
