# Generated by Django 5.2 on 2025-10-22 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResaurantInfo',
            new_name='RestaurantInfo',
        ),
    ]
