# Generated by Django 5.2 on 2025-10-04 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('orders', '0002_remove_orderitem_order_remove_orderitem_menu_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='review',
            name='menu_item',
        ),
        migrations.RemoveField(
            model_name='review',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
