# Generated by Django 5.2 on 2025-11-11 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_menuitem_category'),
        ('orders', '0012_order_waiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='review',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='menu.menuitem'),
        ),
    ]
