# Generated by Django 5.2 on 2025-11-11 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_review_delivery_alter_review_menu_item'),
        ('orders', '0012_order_waiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='orders.order'),
        ),
    ]
