# Generated by Django 5.2 on 2025-11-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_review_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
