# Generated by Django 5.2 on 2025-10-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_shift_shift_type_alter_staff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Cashier', 'Cashier'), ('Waiter', 'Waiter'), ('Chef', 'Chef'), ('DeliveryBoy', 'Delivery Boy'), ('Other', 'Other')], max_length=20),
        ),
    ]
