# Generated by Django 5.2 on 2025-10-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_staff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Cashier', 'Cashier'), ('Waiter', 'Waiter'), ('Chef', 'Chef'), ('DeliveryBoy', 'Delivery Boy')], max_length=20),
        ),
    ]
