# Generated by Django 5.2 on 2025-11-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_staff_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Cashier', 'Cashier'), ('Waiter', 'Waiter'), ('Kitchen_manager', 'Kitchen_manager'), ('DeliveryBoy', 'Delivery Boy'), ('Other', 'Other')], max_length=20),
        ),
    ]
