# Generated by Django 5.2 on 2026-01-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_staff_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
    ]
